Add validation to playbook

diff --git a/ch07/library/go_run b/ch07/library/go_run
--- a/ch07/library/go_run
+++ b/ch07/library/go_run
@@ -12,44 +12,45 @@ if [ -z "$host" ]; then
      exit 1
 fi
 
-if [ -z "$user" ]; then
-     printf '{"busy": false, "changed": false, "failed": true, "msg": "missing required arguments: user"}'
-     exit 1
+# Validation
+if [[ $host == "localhost" ]]; then
+     printf '{"Host": "%s"}' "$host" > $f
+
+     cd state
+     go run main.go ../$f 
+
+# Router configuration
+else
+     if [ -z "$user" ]; then
+          printf '{"busy": false, "changed": false, "failed": true, "msg": "missing required arguments: user"}'
+          exit 1
+     fi
+
+     if [ -z "$password" ]; then
+          printf '{"busy": false, "changed": false, "failed": true, "msg": "missing required arguments: password"}'
+          exit 1
+     fi
+
+     if [ -z "$input" ]; then
+          printf '{"busy": false, "changed": false, "failed": true, "msg": "missing required arguments: input"}'
+          exit 1
+     fi
+
+     printf '{"Host": "%s", "User": "%s", "Password": "%s", "Input": "%s"}' \
+     "$host" "$user" "$password" "$input" > $f
+
+     # Delimiting character for hostnames
+     IFS='-'
+     read -a list <<< "$host"
+
+     # Run Go code with this file as an argument
+     cd ${list[2]}
+     go run main.go ../$f
 fi
-
-if [ -z "$password" ]; then
-     printf '{"busy": false, "changed": false, "failed": true, "msg": "missing required arguments: password"}'
-     exit 1
-fi
-
-if [ -z "$input" ]; then
-     printf '{"busy": false, "changed": false, "failed": true, "msg": "missing required arguments: input"}'
-     exit 1
-fi
-
-#config_input=$(printf '%s' "$input" | base64 -w 0)
-
-# args=$(printf '{"Host": "%s", "User": "%s", "Password": "%s", "Input": "%s"}' \
-#  "$host" "$user" "$password" "$config_input")
-
-# go run main.go "${args}"
-
-# Create temp arguments file
-printf '{"Host": "%s", "User": "%s", "Password": "%s", "Input": "%s"}' \
- "$host" "$user" "$password" "$input" > $f
-
-# Delimiting character for hostnames
-IFS='-'
-read -a list <<< "$host"
-
-# Run Go code with this file as an argument
-cd ${list[2]}
-go run main.go ../$f
-cd ..
 
 # Remove temp arguments file
+cd ..
 rm $f 
-
 
 ## MANUAL INPUTS
 # c=$(cat << EOF
